### ISSUE TITLE
error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pauljamesharper** [Retinazer/packettracer-installer#1]
I am trying to install Cisco Packet Tracer 7.3.0 on Debian 10 Buster. It installs okay using your script ibut I get the following error when I try to start it.

#/opt/pt/bin$ ./PacketTracer7 
./PacketTracer7: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
#

How do I install libjpeg.so.8? Or can the script do that?

**Comment by coleyoungsh** [comment]
libjpeg should be installed by the script. Sorry I was late getting back to you, with everything going on right now I haven't been paying too much attention to this project. When I used PT I was running it on Debian 10 and didn't have any issue, it was my main testing platform.

**Comment by pauljamesharper** [comment]
Apologies from me too. I just tried the script tonight and it just worked. I had run the script multiple times before. 

I only noticed one error:

`./packet-tracer-7.3.0-install.sh: line 18: [: too many arguments
`
But I think you can mark it as resolved. Thanks for your program and your time.

**Comment by coleyoungsh** [comment]
Not a problem!
